parameters:
    env(BUILD): 'local'

services:
    _defaults:
        autowire: false
        autoconfigure: true

    Ecosystem\ApiHelpersBundle\Controller\HealthCheckController:
        arguments: ['%env(string:BUILD)%']

    Ecosystem\ApiHelpersBundle\EventListener\ExceptionListener:
        arguments: ['@logger', '%kernel.debug%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
