parameters:
    # nothing to declare
services:
    Ecosystem\ApiHelpersBundle\EventListener\ExceptionListener:
        arguments: ['@logger', '%kernel.debug%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
