parameters:
    # nothing to declare
services:
    _defaults:
        bind:
            $build: '%env(string:BUILD)%'

    Ecosystem\ApiHelpersBundle\Controller\HealthCheckController:
        arguments: ['%build%']
        tags:
            - { name: controller.service_arguments }

    Ecosystem\ApiHelpersBundle\EventListener\ExceptionListener:
        arguments: ['@logger', '%kernel.debug%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
