parameters:
    env(BUILD): 'local'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\ApiHelpersBundle\Controller\HealthCheckController:
        arguments: ['%env(string:BUILD)%']

    Ecosystem\ApiHelpersBundle\EventListener\ExceptionListener:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Ecosystem\ApiHelpersBundle\EventListener\DTOListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller_arguments }

    Ecosystem\ApiHelpersBundle\Monolog\Processor:
        arguments: ['%env(string:BUILD)%']
