parameters:
    env(BUILD): 'local'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ecosystem\ApiHelpersBundle\Controller\HealthCheckController:
        arguments: ['%env(string:BUILD)%']

    Ecosystem\ApiHelpersBundle\Monolog\Processor:
        arguments: ['%env(string:BUILD)%']
