parameters:
    # nothing to declare
services:
    App\EventListener\ExceptionListener:
        arguments: ['@logger', '%kernel.debug%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
