parameters:
    env(BUILD): 'local'

services:
    Ecosystem\ApiHelpersBundle\Controller\HealthCheckController:
        arguments: ['%env(string:BUILD)%']
        tags:
            - { name: container.service_subscriber }
            - { name: controller.service_arguments }

    Ecosystem\ApiHelpersBundle\EventListener\ExceptionListener:
        arguments: ['@logger', '%kernel.debug%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
